// autogenerated: does not work
/* import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ModalinkPage } from './modalink.page';

describe('ModalinkPage', () => {
  //this does not pass
  let component: ModalinkPage;
  let fixture: ComponentFixture<ModalinkPage>;

  beforeEach(() => {
    fixture = TestBed.createComponent(ModalinkPage);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  //this passes
  it('should pass', () => {
    expect(true).toBe(true);
  });
}); */

//this works
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { IonicModule } from '@ionic/angular';
import { ModalinkPage } from './modalink.page';

describe('ModalinkPage', () => {
  let component: ModalinkPage;
  let fixture: ComponentFixture<ModalinkPage>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [ModalinkPage, HttpClientTestingModule, IonicModule.forRoot()],
    }).compileComponents();

    fixture = TestBed.createComponent(ModalinkPage);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
