/* // autogenerated: does not work
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ModalinkPage } from './modalink.page';

describe('ModalinkPage', () => {
  //this does not pass
  let component: ModalinkPage;
  let fixture: ComponentFixture<ModalinkPage>;

  beforeEach(() => {
    fixture = TestBed.createComponent(ModalinkPage);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  //can't test modal
  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
 */
