name: Production Deploy
run-name: ${{ github.actor }} is deploying to production
on:
  push:
    branches:
      - prod
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
          aws-region: eu-north-1
      - name: Deploy frontend to S3
        run: |
          aws s3 sync ./hosting s3://atra-front --delete
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "This job's status is ${{ job.status }}."
