name: Destroy AWS Infrastructure
run-name: ${{ github.actor }} is destroying AWS infrastructure
on:
  workflow_dispatch:
jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-north-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Delete S3 objects
        continue-on-error: true
        run: |
          aws s3 rm s3://atra-front --recursive
      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm ci  # or yarn install
      - name: Install CDK dependencies
        run: |
          cd backend
          npm install aws-cdk-lib constructs
          npm install --save-dev @types/node
      - name: CDK Destroy
        run: |
          cd backend
          cdk destroy api --force
          cdk destroy cognito --force
          cdk destroy frontend --force
          cdk destroy database --force
          cdk destroy vpc --force
