name: Destroy AWS Infrastructure
run-name: ${{ github.actor }} is destroying AWS infrastructure
on:
  workflow_dispatch:
jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-north-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Destroy Cloudwatch log groups
        run: |
          LOG_GROUPS=$(aws logs describe-log-groups --query "logGroups[].logGroupName" --output text)
          for LOG_GROUP in $LOG_GROUPS; do
            echo "Deleting $LOG_GROUP"
            aws logs delete-log-group --log-group-name "$LOG_GROUP"
          done
      - name: Delete Cognito users and user pools
        run: |
          USER_POOLS=$(aws cognito-idp list-user-pools --max-results 10 --query "UserPools[].Id" --output text)
          for POOL_ID in $USER_POOLS; do
            echo "Processing user pool: $POOL_ID"

            USERS=$(aws cognito-idp list-users --user-pool-id $POOL_ID --query "Users[].Username" --output text)
            for USERNAME in $USERS; do
              echo "Deleting user: $USERNAME from pool: $POOL_ID"
              aws cognito-idp admin-delete-user --user-pool-id $POOL_ID --username $USERNAME
            done
            echo "Deleting user pool: $POOL_ID"
            aws cognito-idp delete-user-pool --user-pool-id $POOL_ID
          done
      - name: Delete S3 objects
        continue-on-error: true
        run: |
          aws s3 rm s3://atra-frontend-bucket --recursive
      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          npm ci  # or yarn install
      - name: Install CDK dependencies
        run: |
          cd backend
          npm install aws-cdk-lib constructs
          npm install --save-dev @types/node
      - name: CDK Destroy
        run: |
          cd backend
          cdk destroy api --force
          # cdk destroy cognito --force
          cdk destroy frontend --force
          cdk destroy database --force
          cdk destroy vpc --force
