name: Hosting Deployment
run-name: ${{ github.actor }} is deploying app to S3
on:
  push:
    branches:
      - prod
jobs:
  Deploy-Prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
      - name: Build Ionic projects
        run: ionic build
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
          aws-region: eu-north-1
      - name: Deploy frontend to S3
        run: |
          aws s3 sync ./hosting s3://atra-frontend-bucket --delete --exact-timestamps
      - run: echo "This job's status is ${{ job.status }}."
